config/routes.rb
Rails.application.routes.draw do
  #The site is oriented around Projects
  resources :projects do
    get "delete"
    get "add_tasks"
  end

  #These pages are necessary to sign in with Google account info
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  #This route allows users to sign out
  resources :sessions, only: [:create, :destroy]
  #This route prevents users from entering the site without signing in
  resource :home, only: [:show]
  #This route sets the home page
  root to: "home#show"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  has_many :success_conditions, :dependent => :destroy
  has_many :users, through: :tasks
  accepts_nested_attributes_for :success_conditions, :allow_destroy => true
  accepts_nested_attributes_for :tasks, :allow_destroy => true
end

app/models/success_condition.rb
class SuccessCondition < ActiveRecord::Base
  belongs_to :project
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :task
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.email = auth.info.email
        # user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if current_user
      redirect_to(projects_path)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :define_user_projects
  # GET /projects
  # GET /projects.json
  def index
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.tasks.build
    @project.success_conditions.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    handle_tasks
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    handle_tasks
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def handle_tasks
    user_ids = ""
    for task in @project.tasks
      if User.where(:email => task.email).first.nil?
        @project.errors.add(:email, "User not found")
      else
        task.user_id = User.where(:email => task.email).first.id
      end
      user_ids += task.user_id.to_s + ", "
    end
    puts user_ids
  end
  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def define_user_projects
    admins = File.read("app/assets/admins.txt")
    if admins.include? current_user.email
      @isAdmin = true
      @projects = Project.all
    else
      @isAdmin = false
      allowed_tasks = Task.includes(:project).where(:user_id => current_user)
      project_ids = ""
      for allowed_task in allowed_tasks
        project_ids += allowed_task.project_id.to_s + ","
      end
      project_ids = project_ids[0..project_ids.length - 2]
      project_ids = project_ids.split(",")
      @projects = Project.find(project_ids)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :id, :success_conditions_attributes => [:id, :project_id, :description, :completed?, :_destroy], :tasks_attributes => [:id, :description, :status, :project_id, :email, :_destroy])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    user = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/show.html.erb
<% if current_user %>
<% else %>
  <h2> Please sign in </h2>
  <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> doitsometi.me</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <a href="<%=projects_path %>"> <h3> Do it sometime </h3> </a>
    <div id="user" >
      <% if current_user %>
      Welcome, <%= current_user.name %>
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
      <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
  </div>
  <div id="sidebar">
    <% if current_user %>
    <div class = "plus-minus-buttons">
      <h1> <%= link_to "Projects", projects_path%> </h1>
      <a onclick="toggleDeleteButtons()" class='button'>
        <%= button_tag do %>
        -
        <% end %>
      </a>
      <%= link_to new_project_path, :class => 'button' do %>
      <%= button_tag "+"%>
      <% end %>
    </div>
    <ul id="projects" data-deleteisshown='false'>
      <% for project in @projects %>
      <li id = "project_<%=project.id %>" > <%= project.name %> <%= link_to ">", project %></li>
      <% end %>
    </ul>
    <p id="notice"><%= notice %></p>
    <% else %>
    <h1> Please sign in </h1>
    <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
    <% end %>
  </div>
  <div id="content">
    <% if current_user %>
    <%= yield %>
    <% end %>
  </div>
</body>
</html>

app/views/projects/_display_errors.html.erb
<% if @project.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
  <ul>
    <%@project.errors.messages.values.each do |msg| %>
        <%msg.each do  |m| %>
          <li><%= m %></li>
        <%end %>
      <% end %>
  </ul>
</div>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= render 'display_errors' %>
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<h3> Success Conditions: </h3>
<ul id="conditions">
  <%=f.fields_for :success_conditions do |builder|%>
  <li class = "">
    <%= builder.label :description %>
    <%= builder.text_field :description %>
    <%= builder.hidden_field :_destroy %>
    <%= link_to "remove", '#', onclick: 'remove_success_condition(this)' %>
  </li>
  <% end %>
</ul>
<%= link_to "Add Success Conditions", '#', onclick: 'add_success_conditions(this)' %> <br/>
<h3> Tasks </h3>
<ul id="tasks">
  <%=f.fields_for :tasks do |builder|%>
    <li class='task'>
    <%= builder.label :description %>
    <%= builder.text_field :description%>
    <%= builder.label :email, "Assign To:" %>
    <%= builder.text_field :email %>
    <%= builder.label :status, "Status:" %>
    <%= builder.select :status, options_for_select(["Not started", "In progress", "Need help", "Complete"]) %>
    <%= link_to "remove", '#', onclick: 'remove_task(this)' %>
  </li>
    <% end %>
</ul>

<%= link_to "Add Tasks", '#', onclick: 'add_tasks(this)' %> <br/>
</br>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2> <%= @project.name %> </h2>
<h3> Success Conditions </h3>
<ul>
  <% for succ_con in @project.success_conditions %>
  <li> <%= succ_con.description %> </li>
  <% end %>
</ul>

<h3> Tasks </h3>
<ul>
  <% for task in @project.tasks %>
    <%= content_tag :li do %>
      <span class = <%= task.status.to_s.downcase.delete(' ') %> >
        <%= task.description + ": " %>
      </span>
      <% if User.where(:id => task.user_id).first.nil? %>
      <%="Unknown user"%>
      <% else %>
      <%="#{User.where(:id => task.user_id).first.name}"%>
      <% end %>
    <% end %>
  <% end %>
</ul>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>